CREATE TABLE escolas_alunos AS
SELECT 
    e.DRE,
    e.CODESC,
    e.TIPOESC,
    e.NOMESC AS NOME_ESCOLA,
    e.DISTRITO AS DISTRITO_ESCOLA,
    e.SETOR AS SETOR_ESCOLA,
    e.LATITUDE,
    e.LONGITUDE,
    a.ANO,
    a.MODAL,
    a.DESCSERIE,
    a.PERIODO,
    a.TURNO,
    a.DESCTURNO,
    a.SEXO,
    a.IDADE,
    a.NEE,
    a.RACA,
    a.Qtde
FROM 
    (SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2010" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2011" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2012" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2013" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2014" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas-dez-2015" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122018" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122019" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122020" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122021" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122022" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolas122023" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolasr34" UNION ALL
     SELECT DRE, CODESC, TIPOESC, NOMESC, DISTRITO, SETOR, LATITUDE, LONGITUDE FROM "escolasr34dez2017") AS e
JOIN 
    (SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeraca-r33" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez17" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez18" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez19" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez20" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez21" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez22" UNION ALL
     SELECT DRE, CODESC, ANO, MODAL, DESCSERIE, PERIODO, TURNO, DESCTURNO, SEXO, IDADE, NEE, RACA, Qtde FROM "idadeserieneeracadez23") AS a
ON 
    e.DRE = a.DRE AND e.CODESC = a.CODESC;